### PR TITLE
parent return type

### LINKED ISSUE #465: `parent` keyword is getting scoped
## Bug report

| Question    | Answer
| ------------| ---------------
| PHP-Box version | 3.11.1
| PHP version | 7.2, 7.3, 7.4 (8.0 seems to work)
| Platform with version | Ubuntu
| Github Repo | [captainhookphp/captainhook](https://github.com/captainhookphp/captainhook)

During the scoping process of `Symfony\String` `5.2` classes that use `parent` as type hint the `parent` keyword  is getting  scoped to `PREFIX\parent`

```
PHP Fatal error:  Cannot use 'CaptainHook\Ext\parent' as class name as it is reserved in phar:///home/runner/work/captainhook/captainhook/build/phar/captainhook.phar/vendor/symfony/string/UnicodeString.php on line 166
16
Error: Process completed with exit code 255.
```
You can look at the full build result [here](https://github.com/captainhookphp/captainhook/runs/2231699832?check_suite_focus=true)

Original Symfony code
```php
public function normalize(int $form = self::NFC): parent
{
        $str = clone $this;
    ...
}
```

Scoped version
```php
public function normalize(int $form = self::NFC) : \CaptainHook\Ext\parent
{
    $str = clone $this;
    ...
}
```

The `parent` keyword should not be scoped.

Thanks :)

### PR DESCRIPTION
**Pull request by smoench**
resolves #465

### CODE REVIEW

**Comment by theofidry** [comment]
Thanks!

**Comment by bobthecow** [comment]
@theofidry can we get a release tagged to fix the PaySH builds? 😁

**Comment by theofidry** [comment]
I'll try tonight if I don't finish off too late. Sorry for the delay there's been a lot of notifications & mails build up in a few weeks of vacation 😅

**Comment by sebastianfeldmann** [comment]
Thanks for the release any chance of getting a Box release as well with the updated 0.14.1 😇

**Pull request merged**
