### PR TITLE
Removed file extension

### PR DESCRIPTION
**Pull request by Nyholm**
Fixes the error: 

> Skipped installation of bin bin/php-scoper for package humbug/php-scoper: file not found in package

### CODE REVIEW

**Comment by Nyholm** [comment]
Oh, you beat me with over 9 hours

**Comment by theofidry** [comment]
Meh, soz I didn't write the complete message. I meant it should be fine after #69 not that #69 replaces it :)

**Comment by Nyholm** [comment]
Thank you for merging

**Comment by theofidry** [comment]
Thanks for the PR :)

**Pull request merged**
