### PR TITLE
fix: Preserve heredoc/newdoc indentation

### PR DESCRIPTION
**Pull request by theofidry**

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Is this related to https://github.com/sebastianbergmann/phpunit/issues/5855? If so, how can I test that it fixes my issue? Thanks!

**Comment by theofidry** [comment]
@sebastianbergmann yes I expect it to solve it. I've released it in 0.18.13

**Comment by sebastianbergmann** [comment]
No, sorry: https://github.com/sebastianbergmann/phpunit/actions/runs/9467129772/job/26080647235

**Comment by theofidry** [comment]
Ah yes ofc... Needs something more

**Pull request merged**
