### PR TITLE
Fix AppVeyor builds

### PR DESCRIPTION
**Pull request by theofidry**

### CODE REVIEW

**Comment by theofidry** [comment]
@padraic could you give me access to AppVeyor so that I could interrupt AppVeyor builds when necessary?

**Comment by padraic** [comment]
@theofidry Can you check now? Added @humbug/core members as a role to PHP Scoper there.

**Comment by theofidry** [comment]
Got it. If someone of the @humbug/core knows how to set up Make for Windows... that would be helpful...

I don't have a Windows machine at all so trying to do it and waiting on AppVeyor each time is a real pain as AppVeyor is super slow

**Comment by padraic** [comment]
I was really hoping not to have to boot up Windows for anything other than Subnautica today ;).

**Comment by theofidry** [comment]
Fortunately it just worked, that's a good game btw :)

**Pull request merged**
