### PR TITLE
Revert "Add versions to hot-patched symbols" but keep fixed Lexer

### PR DESCRIPTION
**Pull request by smoench**
I was wrong with the Reflector approach. It will prevent us scoping the php-parser.

It is related to https://github.com/box-project/box/pull/499

### CODE REVIEW

**Comment by smoench** [comment]
Can someone have a look why phpstan fails? Something happened with the Makefile? It worked when I had contributed it.

**Comment by theofidry** [comment]
Could you elaborate a bit on what's going on? I'm not sure to understand the back & forth here...

**Comment by smoench** [comment]
php-parser uses and defines internally T_FN, T_MATCH and so forth constants. In case your scoping php-parser those constants (e.g. `Humbug123\T_FN`) would be scoped but php-parser still defines them on runtime without the scoped namespace. Then box will fail as `Humbug123\T_FN` constant is not defined.

**Comment by theofidry** [comment]
>Then box will fail as Humbug123\T_FN constant is not defined.

Why is that? If PHP-Parser still relies on defining them at runtime won't both (scoped & non-scoped symbols) be found?

**Comment by smoench** [comment]
They are defined on runtime when they are not presented so they are stored as strings -> https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Lexer.php#L413

**Comment by theofidry** [comment]
Sorry for the delay @smoench, thanks for the PR

**Pull request merged**
