### PR TITLE
[DO NOT MERGE] Prototype of the first MVP

### PR DESCRIPTION
**Pull request by theofidry**
I played a bit with this library in the train to see what is really missing and attempt to make some progress. Whilst this PR should not be merged directly, some of its changes should be cherry-picked and merge via smaller and more scoped PRs.

<hr>

What the main changes are about:

- Change the build (for generating the PHAR) process of php-scoper to
apply itself in order to isolate its deps
- Tweak the command to make it more usable and fix some stuffs
- Scope all files even non-PHP one (or rather dump them as well, they
don't need to be isolated)
- Show file path when a parse error occurrs
- Fix progress bar

@padraic I'm quite satisfied overall and I don't think we are missing much for 1.0.0. The tweaks done here are the mostly it, the only blocking thing I see for now is:

- Fixing the namespacing in strings, necessary at least for the Composer autoloading otherwise the classmap used is wrong
- Allowing the whitelisting of some namespaces/classes to make it usable with applications like PhpUnit

We will need a proper test for the second case at some point. For the first one, a good test is to actually run the build process of the PHAR for php-scoper itself where in this PR I apply the scoping first, and build the PHAR from the scoped files.

### CODE REVIEW

**Comment by theofidry** [comment]
Note that an alternative to fixing the classmap directly is to fix the `composer.json` like suggested in #5 which can actually may turn out to be much easier.

**Comment by padraic** [comment]
I'd certainly go with fixing composer.json and see if that suffices.

**Comment by theofidry** [comment]
Wouldn't that require to dump the autoloader again though?

**Comment by theofidry** [comment]
Closed in favour of #40, #41, #42

**Pull request closed without merging**
