### PR TITLE
Upgrade to Php parser 4

### PR DESCRIPTION
**Pull request by TomasVotruba**
This PR waits on BetterReflection to be tagged. Ready otherwise

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ref https://github.com/Roave/BetterReflection/pull/410

**Comment by TomasVotruba** [comment]
It's ready

https://github.com/Roave/BetterReflection/releases/tag/3.0.0

**Comment by TomasVotruba** [comment]
Any ETA?

**Comment by theofidry** [comment]
Sorry missed your comment from yesterday. One rebase and I think we're ready to go

**Comment by theofidry** [comment]
Thanks you @TomasVotruba!

**Pull request merged**
