### PR TITLE
Test against php 7.4

### PR DESCRIPTION
**Pull request by BackEndTea**
Nightly build is for php 8.0.
7.4 has its own branch now

### CODE REVIEW

**Comment by theofidry** [comment]
Thanks! let's remove the nightly build then :)

**Comment by BackEndTea** [comment]
Works for me, as long as it gets added once php 8.0 is getting close 😄

**Comment by BackEndTea** [comment]
Thank you @theofidry

**Comment by theofidry** [comment]
Thank you for all the PRs :)

**Pull request merged**
