### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by theofidry**

### CODE REVIEW

**Comment by theofidry** [comment]
Hm apparently the new version of Infection requires PHP 7.4... WDYT of bumping PHP-Scoper as well to that version @villfa @smoench?

**Comment by smoench** [comment]
Let us fix #425 first :-)

**Comment by theofidry** [comment]
Actually the Symfony build is failing due to that so indeed it will wait for it :P

**Comment by villfa** [comment]
> Hm apparently the new version of Infection requires PHP 7.4... WDYT of bumping PHP-Scoper as well to that version?

I don't have a strong opinion about that.
I'm just a bit worried about the inconvenience it may cause to the users of *php-scoper* and *box* (since *box* will have to follow the move), especially there is no docker image provided.

**Comment by smoench** [comment]
Sorry, @theofidry you are doing here a bit too much so I created #428 and #429 😬

**Pull request merged**
