### PR TITLE
WIP: Bump to PHP 8.1

### LINKED ISSUE #583: Bump min version to PHP 8.0 or 8.1
As infection bumps it to 8.1 and it is encouraged to use the latest version for PHP-Scoper/Box, might as well run on 8.1

A few other things to bump as a result the Symfony deps can be bumped from 5.4.* to 6.*:

- [ ] fixtures set016
- [ ] fixtures set017
- [ ] fixtures set019

### PR DESCRIPTION
**Pull request by theofidry**
Closes #583

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, we're waiting for this one with Rector, ECS and 3 more tools last year.
Any ETA? :)

**Comment by TomasVotruba** [comment]
I'd love to check the failing builds and help. Yet they're deleted at long time ago. Could you trigger the CI?

**Comment by theofidry** [comment]
Hi @TomasVotruba,

I've managed to upgrade Box to 8.1 & FidryConsole 0.5 which were the main blockers remaining. I'm working on finishing that new release for Box and then I can wrap it up for PHP-Scoper as well I think.

**Comment by TomasVotruba** [comment]
Hi @theofidry , thanks for reaching out and working on this. The scoper 0.17 was a huge improvement to cleanup configs, so I look forward for next one too 👍

**Comment by theofidry** [comment]
Closed via #679

**Pull request closed without merging**
