### PR TITLE
Replace PHP-Scoper name resolver by the PHP-Parser one (Part 1)

### PR DESCRIPTION
**Pull request by theofidry**
This is a continuation of #400 but taking an easier starting path. I had some misunderstanding about PHP-Parser's name resolver, and from the doc (see https://github.com/nikic/PHP-Parser/blob/master/doc/component/Name_resolution.markdown#name-resolution) it actually replaces all name nodes by its fully qualified form whenever possible. Whilst it's possible to toggle off the replace, I believe this will lead to simpler cases in PHP-Scoper so we might as well go for it.

However it currently breaks all the tests so need to fix that first

### CODE REVIEW

**Comment by theofidry** [comment]
@marekdedic I believe quite a few cases broken related to not adding prefixes. I'm trying to look at it but can't find a solution at the moment. If you have any lead it would be very welcomed

**Comment by marekdedic** [comment]
Hi,
I will try to fix what I broke... :D

Any good place where to start? E. g. a test that fails because of prefixes...

**Comment by theofidry** [comment]
I'm really not sure... This PR is kinda of a start from #400 already :P i couldn't check in much more details after scoping this down a bit

**Comment by theofidry** [comment]
@marekdedic I think I have a good lead, I hope I will have something out very soon

**Comment by theofidry** [comment]
There is more changes & cleanup I wish to do but this PR is the first step and doing the strict minimum: register the PHP-Parser name resolver visitor and fixing the tests

**Comment by marekdedic** [comment]
Hi,
I looked at the failing tests and it seems to me that they have nothing to do with prefixing - I see
```php
Fatal error: Uncaught Error: Call to undefined method Humbug\PhpScoper\Configuration::load() in /home/user/php-scoper/vendor/humbug/box/src/Configuration/Configuration.php:2700
```
Looking at the file in question, it seems like an issue with box - it tries to call a non-existent method.

I can't see how this is related to any of the changes you made though...

**Comment by theofidry** [comment]
No the e2e tests failure are expected: it's due to a BC break of the config

**Comment by marekdedic** [comment]
Ok, ok, so is there any issue with the "simplified" prefixes then?

**Comment by theofidry** [comment]
Not that I can see unless you see any offender there in the change of the tests

**Review by marekdedic — APPROVED** [review]
LGTM!

I am still a bit confused by whitelisting, though...

**Comment by theofidry** [comment]
I'll come up with a rename to remove the confusion hopefully

**Pull request merged**
