### PR TITLE
Fix group use bug

### PR DESCRIPTION
**Pull request by ngyuki**
See https://github.com/nikic/PHP-Parser/blob/f66a32e2df7866d593fa7a1bb582348f772511b0/lib/PhpParser/Node/Stmt/Use_.php#L9-L14

Need check `type` both `$use_` and `$useStatement`.

Fixes box-project/box#476

### CODE REVIEW

**Review by theofidry — APPROVED** [review]

**Comment by theofidry** [comment]
Thanks a lot for the quick PR @ngyuki; sorry for the delay I'm a bit underwatter atm. Could you apply the Style CI changes? I'll merge & release it right away once it's green

**Comment by ngyuki** [comment]
@theofidry Thank you for review.
I applied styleci patch.

**Comment by theofidry** [comment]
Thank you @ngyuki!

**Comment by theofidry** [comment]
And released

**Pull request merged**
